### ISSUE TITLE
Scrollbar for the sidebar

### ISSUE THREAD

**Issue by jony0008** [bitprophet/alabaster#106]
When the sidebar is fixed and get full it would be good if it was scrollable so it is possible to see the whole content.

**Comment by davidhassell** [comment]
Hello - is this issue still being considered? It would be a great enhancement for my project. Thanks

**Comment by kazesberger** [comment]
you can add a custom css resource and add appropriate styles with it to the sidebar:
https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

```css
div.sphinxsidebar {
  height: 100vh;
  overflow: auto;
}
```
