### ISSUE TITLE
Object definitions look very out of place

### ISSUE THREAD

**Issue by CendioOssman** [bitprophet/alabaster#184]
For object references, alabaster uses this styling (since objects are wrapped in a `<code>`):

```css
pre, tt, code {
    font-family: 'Consolas', 'Menlo', 'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', monospace;
    font-size: 0.9em;
}
```

This styling is very appropriate as the monospace font looks larger than the other text otherwise.

However object ''definitions'', Sphinx never uses a `<code>` element, insted applying the monospace font to the  `<dt class="sig">` element. This makes the definitions look very out of place as the text for those is much larger.

Since monospace and a font size reduction go hand in hand, I would suggest that Alabaster needs this addition:

```css
.sig {
    font-size: 0.9em;
}
```

I wonder if these lines were originally supposed to handle this, and the HTML build has changed what it outputs since then:

https://github.com/bitprophet/alabaster/blob/6a0a56ffe79bd039085e1ad7ed26da5b217bd4ab/alabaster/static/alabaster.css_t#L399-L401
